version: "3.1"

services:
  jenkins-agent:
    container_name: jenkins-agent
    build: .
    restart: always
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:

networks:
  jenkins:

volumes:
  jenkins-data:
